spring.application.name=Teatro_Backend-1
spring.datasource.url=jdbc:postgresql://localhost:5432/teatro
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
